#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickFood.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="quickFoodDB")]
	public partial class quickfoodDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Insertmesero(mesero instance);
    partial void Updatemesero(mesero instance);
    partial void Deletemesero(mesero instance);
    partial void Insertpedido(pedido instance);
    partial void Updatepedido(pedido instance);
    partial void Deletepedido(pedido instance);
    partial void Insertpedidodetalle(pedidodetalle instance);
    partial void Updatepedidodetalle(pedidodetalle instance);
    partial void Deletepedidodetalle(pedidodetalle instance);
    partial void Insertplato(plato instance);
    partial void Updateplato(plato instance);
    partial void Deleteplato(plato instance);
    #endregion
		
		public quickfoodDataContext() : 
				base(global::QuickFood.Properties.Settings.Default.quickFoodDBConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public quickfoodDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quickfoodDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quickfoodDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quickfoodDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cliente> cliente
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<mesero> mesero
		{
			get
			{
				return this.GetTable<mesero>();
			}
		}
		
		public System.Data.Linq.Table<pedido> pedido
		{
			get
			{
				return this.GetTable<pedido>();
			}
		}
		
		public System.Data.Linq.Table<pedidodetalle> pedidodetalle
		{
			get
			{
				return this.GetTable<pedidodetalle>();
			}
		}
		
		public System.Data.Linq.Table<plato> plato
		{
			get
			{
				return this.GetTable<plato>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cliente")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cltId;
		
		private string _cltNombre;
		
		private string _cltTelefono;
		
		private string _cltDireccion;
		
		private string _cltIdentificacion;
		
		private EntitySet<pedido> _pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncltIdChanging(int value);
    partial void OncltIdChanged();
    partial void OncltNombreChanging(string value);
    partial void OncltNombreChanged();
    partial void OncltTelefonoChanging(string value);
    partial void OncltTelefonoChanged();
    partial void OncltDireccionChanging(string value);
    partial void OncltDireccionChanged();
    partial void OncltIdentificacionChanging(string value);
    partial void OncltIdentificacionChanged();
    #endregion
		
		public cliente()
		{
			this._pedido = new EntitySet<pedido>(new Action<pedido>(this.attach_pedido), new Action<pedido>(this.detach_pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cltId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cltId
		{
			get
			{
				return this._cltId;
			}
			set
			{
				if ((this._cltId != value))
				{
					this.OncltIdChanging(value);
					this.SendPropertyChanging();
					this._cltId = value;
					this.SendPropertyChanged("cltId");
					this.OncltIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cltNombre", DbType="VarChar(200)")]
		public string cltNombre
		{
			get
			{
				return this._cltNombre;
			}
			set
			{
				if ((this._cltNombre != value))
				{
					this.OncltNombreChanging(value);
					this.SendPropertyChanging();
					this._cltNombre = value;
					this.SendPropertyChanged("cltNombre");
					this.OncltNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cltTelefono", DbType="VarChar(20)")]
		public string cltTelefono
		{
			get
			{
				return this._cltTelefono;
			}
			set
			{
				if ((this._cltTelefono != value))
				{
					this.OncltTelefonoChanging(value);
					this.SendPropertyChanging();
					this._cltTelefono = value;
					this.SendPropertyChanged("cltTelefono");
					this.OncltTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cltDireccion", DbType="VarChar(300)")]
		public string cltDireccion
		{
			get
			{
				return this._cltDireccion;
			}
			set
			{
				if ((this._cltDireccion != value))
				{
					this.OncltDireccionChanging(value);
					this.SendPropertyChanging();
					this._cltDireccion = value;
					this.SendPropertyChanged("cltDireccion");
					this.OncltDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cltIdentificacion", DbType="VarChar(20)")]
		public string cltIdentificacion
		{
			get
			{
				return this._cltIdentificacion;
			}
			set
			{
				if ((this._cltIdentificacion != value))
				{
					this.OncltIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._cltIdentificacion = value;
					this.SendPropertyChanged("cltIdentificacion");
					this.OncltIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_pedido", Storage="_pedido", ThisKey="cltId", OtherKey="cltId")]
		public EntitySet<pedido> pedido
		{
			get
			{
				return this._pedido;
			}
			set
			{
				this._pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pedido(pedido entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_pedido(pedido entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mesero")]
	public partial class mesero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _msrId;
		
		private string _msrNombre;
		
		private string _msrIdentificacion;
		
		private EntitySet<pedido> _pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmsrIdChanging(int value);
    partial void OnmsrIdChanged();
    partial void OnmsrNombreChanging(string value);
    partial void OnmsrNombreChanged();
    partial void OnmsrIdentificacionChanging(string value);
    partial void OnmsrIdentificacionChanged();
    #endregion
		
		public mesero()
		{
			this._pedido = new EntitySet<pedido>(new Action<pedido>(this.attach_pedido), new Action<pedido>(this.detach_pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msrId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int msrId
		{
			get
			{
				return this._msrId;
			}
			set
			{
				if ((this._msrId != value))
				{
					this.OnmsrIdChanging(value);
					this.SendPropertyChanging();
					this._msrId = value;
					this.SendPropertyChanged("msrId");
					this.OnmsrIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msrNombre", DbType="VarChar(200)")]
		public string msrNombre
		{
			get
			{
				return this._msrNombre;
			}
			set
			{
				if ((this._msrNombre != value))
				{
					this.OnmsrNombreChanging(value);
					this.SendPropertyChanging();
					this._msrNombre = value;
					this.SendPropertyChanged("msrNombre");
					this.OnmsrNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msrIdentificacion", DbType="VarChar(20)")]
		public string msrIdentificacion
		{
			get
			{
				return this._msrIdentificacion;
			}
			set
			{
				if ((this._msrIdentificacion != value))
				{
					this.OnmsrIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._msrIdentificacion = value;
					this.SendPropertyChanged("msrIdentificacion");
					this.OnmsrIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mesero_pedido", Storage="_pedido", ThisKey="msrId", OtherKey="msrId")]
		public EntitySet<pedido> pedido
		{
			get
			{
				return this._pedido;
			}
			set
			{
				this._pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pedido(pedido entity)
		{
			this.SendPropertyChanging();
			entity.mesero = this;
		}
		
		private void detach_pedido(pedido entity)
		{
			this.SendPropertyChanging();
			entity.mesero = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pedido")]
	public partial class pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pddId;
		
		private System.Nullable<System.DateTime> _pddFecha;
		
		private string _pddEstado;
		
		private System.Nullable<int> _cltId;
		
		private System.Nullable<int> _msrId;
		
		private System.Nullable<decimal> _pddTotal;
		
		private EntitySet<pedidodetalle> _pedidodetalle;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<mesero> _mesero;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpddIdChanging(int value);
    partial void OnpddIdChanged();
    partial void OnpddFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnpddFechaChanged();
    partial void OnpddEstadoChanging(string value);
    partial void OnpddEstadoChanged();
    partial void OncltIdChanging(System.Nullable<int> value);
    partial void OncltIdChanged();
    partial void OnmsrIdChanging(System.Nullable<int> value);
    partial void OnmsrIdChanged();
    partial void OnpddTotalChanging(System.Nullable<decimal> value);
    partial void OnpddTotalChanged();
    #endregion
		
		public pedido()
		{
			this._pedidodetalle = new EntitySet<pedidodetalle>(new Action<pedidodetalle>(this.attach_pedidodetalle), new Action<pedidodetalle>(this.detach_pedidodetalle));
			this._cliente = default(EntityRef<cliente>);
			this._mesero = default(EntityRef<mesero>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pddId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pddId
		{
			get
			{
				return this._pddId;
			}
			set
			{
				if ((this._pddId != value))
				{
					this.OnpddIdChanging(value);
					this.SendPropertyChanging();
					this._pddId = value;
					this.SendPropertyChanged("pddId");
					this.OnpddIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pddFecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> pddFecha
		{
			get
			{
				return this._pddFecha;
			}
			set
			{
				if ((this._pddFecha != value))
				{
					this.OnpddFechaChanging(value);
					this.SendPropertyChanging();
					this._pddFecha = value;
					this.SendPropertyChanged("pddFecha");
					this.OnpddFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pddEstado", DbType="VarChar(20)")]
		public string pddEstado
		{
			get
			{
				return this._pddEstado;
			}
			set
			{
				if ((this._pddEstado != value))
				{
					this.OnpddEstadoChanging(value);
					this.SendPropertyChanging();
					this._pddEstado = value;
					this.SendPropertyChanged("pddEstado");
					this.OnpddEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cltId", DbType="Int")]
		public System.Nullable<int> cltId
		{
			get
			{
				return this._cltId;
			}
			set
			{
				if ((this._cltId != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncltIdChanging(value);
					this.SendPropertyChanging();
					this._cltId = value;
					this.SendPropertyChanged("cltId");
					this.OncltIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msrId", DbType="Int")]
		public System.Nullable<int> msrId
		{
			get
			{
				return this._msrId;
			}
			set
			{
				if ((this._msrId != value))
				{
					if (this._mesero.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmsrIdChanging(value);
					this.SendPropertyChanging();
					this._msrId = value;
					this.SendPropertyChanged("msrId");
					this.OnmsrIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pddTotal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pddTotal
		{
			get
			{
				return this._pddTotal;
			}
			set
			{
				if ((this._pddTotal != value))
				{
					this.OnpddTotalChanging(value);
					this.SendPropertyChanging();
					this._pddTotal = value;
					this.SendPropertyChanged("pddTotal");
					this.OnpddTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pedido_pedidodetalle", Storage="_pedidodetalle", ThisKey="pddId", OtherKey="pddId")]
		public EntitySet<pedidodetalle> pedidodetalle
		{
			get
			{
				return this._pedidodetalle;
			}
			set
			{
				this._pedidodetalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_pedido", Storage="_cliente", ThisKey="cltId", OtherKey="cltId", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.pedido.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.pedido.Add(this);
						this._cltId = value.cltId;
					}
					else
					{
						this._cltId = default(Nullable<int>);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mesero_pedido", Storage="_mesero", ThisKey="msrId", OtherKey="msrId", IsForeignKey=true)]
		public mesero mesero
		{
			get
			{
				return this._mesero.Entity;
			}
			set
			{
				mesero previousValue = this._mesero.Entity;
				if (((previousValue != value) 
							|| (this._mesero.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mesero.Entity = null;
						previousValue.pedido.Remove(this);
					}
					this._mesero.Entity = value;
					if ((value != null))
					{
						value.pedido.Add(this);
						this._msrId = value.msrId;
					}
					else
					{
						this._msrId = default(Nullable<int>);
					}
					this.SendPropertyChanged("mesero");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pedidodetalle(pedidodetalle entity)
		{
			this.SendPropertyChanging();
			entity.pedido = this;
		}
		
		private void detach_pedidodetalle(pedidodetalle entity)
		{
			this.SendPropertyChanging();
			entity.pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pedidodetalle")]
	public partial class pedidodetalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pdeId;
		
		private string _pdeDescripcion;
		
		private System.Nullable<int> _pddId;
		
		private System.Nullable<int> _pltId;
		
		private System.Nullable<int> _pdeCantidad;
		
		private EntityRef<pedido> _pedido;
		
		private EntityRef<plato> _plato;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpdeIdChanging(int value);
    partial void OnpdeIdChanged();
    partial void OnpdeDescripcionChanging(string value);
    partial void OnpdeDescripcionChanged();
    partial void OnpddIdChanging(System.Nullable<int> value);
    partial void OnpddIdChanged();
    partial void OnpltIdChanging(System.Nullable<int> value);
    partial void OnpltIdChanged();
    partial void OnpdeCantidadChanging(System.Nullable<int> value);
    partial void OnpdeCantidadChanged();
    #endregion
		
		public pedidodetalle()
		{
			this._pedido = default(EntityRef<pedido>);
			this._plato = default(EntityRef<plato>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pdeId
		{
			get
			{
				return this._pdeId;
			}
			set
			{
				if ((this._pdeId != value))
				{
					this.OnpdeIdChanging(value);
					this.SendPropertyChanging();
					this._pdeId = value;
					this.SendPropertyChanged("pdeId");
					this.OnpdeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdeDescripcion", DbType="VarChar(255)")]
		public string pdeDescripcion
		{
			get
			{
				return this._pdeDescripcion;
			}
			set
			{
				if ((this._pdeDescripcion != value))
				{
					this.OnpdeDescripcionChanging(value);
					this.SendPropertyChanging();
					this._pdeDescripcion = value;
					this.SendPropertyChanged("pdeDescripcion");
					this.OnpdeDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pddId", DbType="Int")]
		public System.Nullable<int> pddId
		{
			get
			{
				return this._pddId;
			}
			set
			{
				if ((this._pddId != value))
				{
					if (this._pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpddIdChanging(value);
					this.SendPropertyChanging();
					this._pddId = value;
					this.SendPropertyChanged("pddId");
					this.OnpddIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pltId", DbType="Int")]
		public System.Nullable<int> pltId
		{
			get
			{
				return this._pltId;
			}
			set
			{
				if ((this._pltId != value))
				{
					if (this._plato.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpltIdChanging(value);
					this.SendPropertyChanging();
					this._pltId = value;
					this.SendPropertyChanged("pltId");
					this.OnpltIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdeCantidad", DbType="Int")]
		public System.Nullable<int> pdeCantidad
		{
			get
			{
				return this._pdeCantidad;
			}
			set
			{
				if ((this._pdeCantidad != value))
				{
					this.OnpdeCantidadChanging(value);
					this.SendPropertyChanging();
					this._pdeCantidad = value;
					this.SendPropertyChanged("pdeCantidad");
					this.OnpdeCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pedido_pedidodetalle", Storage="_pedido", ThisKey="pddId", OtherKey="pddId", IsForeignKey=true)]
		public pedido pedido
		{
			get
			{
				return this._pedido.Entity;
			}
			set
			{
				pedido previousValue = this._pedido.Entity;
				if (((previousValue != value) 
							|| (this._pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pedido.Entity = null;
						previousValue.pedidodetalle.Remove(this);
					}
					this._pedido.Entity = value;
					if ((value != null))
					{
						value.pedidodetalle.Add(this);
						this._pddId = value.pddId;
					}
					else
					{
						this._pddId = default(Nullable<int>);
					}
					this.SendPropertyChanged("pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="plato_pedidodetalle", Storage="_plato", ThisKey="pltId", OtherKey="pltId", IsForeignKey=true)]
		public plato plato
		{
			get
			{
				return this._plato.Entity;
			}
			set
			{
				plato previousValue = this._plato.Entity;
				if (((previousValue != value) 
							|| (this._plato.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._plato.Entity = null;
						previousValue.pedidodetalle.Remove(this);
					}
					this._plato.Entity = value;
					if ((value != null))
					{
						value.pedidodetalle.Add(this);
						this._pltId = value.pltId;
					}
					else
					{
						this._pltId = default(Nullable<int>);
					}
					this.SendPropertyChanged("plato");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.plato")]
	public partial class plato : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pltId;
		
		private string _pltDescripcion;
		
		private System.Nullable<decimal> _pltPrecio;
		
		private EntitySet<pedidodetalle> _pedidodetalle;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpltIdChanging(int value);
    partial void OnpltIdChanged();
    partial void OnpltDescripcionChanging(string value);
    partial void OnpltDescripcionChanged();
    partial void OnpltPrecioChanging(System.Nullable<decimal> value);
    partial void OnpltPrecioChanged();
    #endregion
		
		public plato()
		{
			this._pedidodetalle = new EntitySet<pedidodetalle>(new Action<pedidodetalle>(this.attach_pedidodetalle), new Action<pedidodetalle>(this.detach_pedidodetalle));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pltId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pltId
		{
			get
			{
				return this._pltId;
			}
			set
			{
				if ((this._pltId != value))
				{
					this.OnpltIdChanging(value);
					this.SendPropertyChanging();
					this._pltId = value;
					this.SendPropertyChanged("pltId");
					this.OnpltIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pltDescripcion", DbType="VarChar(200)")]
		public string pltDescripcion
		{
			get
			{
				return this._pltDescripcion;
			}
			set
			{
				if ((this._pltDescripcion != value))
				{
					this.OnpltDescripcionChanging(value);
					this.SendPropertyChanging();
					this._pltDescripcion = value;
					this.SendPropertyChanged("pltDescripcion");
					this.OnpltDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pltPrecio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pltPrecio
		{
			get
			{
				return this._pltPrecio;
			}
			set
			{
				if ((this._pltPrecio != value))
				{
					this.OnpltPrecioChanging(value);
					this.SendPropertyChanging();
					this._pltPrecio = value;
					this.SendPropertyChanged("pltPrecio");
					this.OnpltPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="plato_pedidodetalle", Storage="_pedidodetalle", ThisKey="pltId", OtherKey="pltId")]
		public EntitySet<pedidodetalle> pedidodetalle
		{
			get
			{
				return this._pedidodetalle;
			}
			set
			{
				this._pedidodetalle.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pedidodetalle(pedidodetalle entity)
		{
			this.SendPropertyChanging();
			entity.plato = this;
		}
		
		private void detach_pedidodetalle(pedidodetalle entity)
		{
			this.SendPropertyChanging();
			entity.plato = null;
		}
	}
}
#pragma warning restore 1591
